DBG_API_ID_REV = {}
DBG_API_REV = {}

# I2CS API Identifiers
DBG_DEV_I2CS_API_ID = 0
DBG_DEV_I2CS_API = {}
DBG_DEV_I2CS_API["I2CS_INITSTART"] = 0
DBG_DEV_I2CS_API["I2CS_DEINIT"] = 1
DBG_DEV_I2CS_API["I2C2_ENABLEACKNOWLEDGE"] = 2
DBG_DEV_I2CS_API["I2C2_DISABLEACKNOWLEDGE"] = 3

# I2CS Reverse Lookup
DBG_API_ID_REV[0] = "DEV_I2CS"
DBG_API_REV["DEV_I2CS"] = {}
DBG_API_REV["DEV_I2CS"][0] = "I2CS_INITSTART"
DBG_API_REV["DEV_I2CS"][1] = "I2CS_DEINIT"
DBG_API_REV["DEV_I2CS"][2] = "I2C2_ENABLEACKNOWLEDGE"
DBG_API_REV["DEV_I2CS"][3] = "I2C2_DISABLEACKNOWLEDGE"
# I2CM API Identifiers
DBG_DEV_I2CM_API_ID = 1
DBG_DEV_I2CM_API = {}
DBG_DEV_I2CM_API["I2CM_INITSTART"] = 0
DBG_DEV_I2CM_API["I2CM_DEINIT"] = 1
DBG_DEV_I2CM_API["I2CM_WRITE"] = 2
DBG_DEV_I2CM_API["I2CM_READ"] = 3
DBG_DEV_I2CM_API["I2CM_READ_SR"] = 4
DBG_DEV_I2CM_API["I2CM_ISDEVICEREADY"] = 5

# I2CM Reverse Lookup
DBG_API_ID_REV[1] = "DEV_I2CM"
DBG_API_REV["DEV_I2CM"] = {}
DBG_API_REV["DEV_I2CM"][0] = "I2CM_INITSTART"
DBG_API_REV["DEV_I2CM"][1] = "I2CM_DEINIT"
DBG_API_REV["DEV_I2CM"][2] = "I2CM_WRITE"
DBG_API_REV["DEV_I2CM"][3] = "I2CM_READ"
DBG_API_REV["DEV_I2CM"][4] = "I2CM_READ_SR"
DBG_API_REV["DEV_I2CM"][5] = "I2CM_ISDEVICEREADY"
# DBG API Identifiers
DBG_SYS_DBG_API_ID = 64
DBG_SYS_DBG_API = {}
DBG_SYS_DBG_API["DBG_INITOS"] = 0
DBG_SYS_DBG_API["DBG_ITER"] = 1

# DBG Reverse Lookup
DBG_API_ID_REV[64] = "SYS_DBG"
DBG_API_REV["SYS_DBG"] = {}
DBG_API_REV["SYS_DBG"][0] = "DBG_INITOS"
DBG_API_REV["SYS_DBG"][1] = "DBG_ITER"
